{"name": "test_error", "status": "broken", "statusDetails": {"message": "Exception: error occurred", "trace": "def test_error():\n>       raise Exception('error occurred')\nE       Exception: error occurred\n\n07-集成allure.py:14: Exception"}, "start": 1719210084079, "stop": 1719210084079, "uuid": "1bf43d97-3f2c-48f1-b9b8-eb7a39354815", "historyId": "97cf4b4fe43e65ffc2215029d3f70515", "testCaseId": "97cf4b4fe43e65ffc2215029d3f70515", "fullName": "07-集成allure#test_error", "labels": [{"name": "suite", "value": "07-集成allure"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "12760-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "07-集成allure"}]}