{"name": "test_error", "status": "broken", "statusDetails": {"message": "Exception: error occurred", "trace": "def test_error():\n>       raise Exception('error occurred')\nE       Exception: error occurred\n\n07-集成allure.py:14: Exception"}, "start": 1719210255730, "stop": 1719210255730, "uuid": "c7db6a78-0ebc-4d46-8d39-0261cfacca61", "historyId": "97cf4b4fe43e65ffc2215029d3f70515", "testCaseId": "97cf4b4fe43e65ffc2215029d3f70515", "fullName": "07-集成allure#test_error", "labels": [{"name": "suite", "value": "07-集成allure"}, {"name": "host", "value": "MSI"}, {"name": "thread", "value": "19916-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "07-集成allure"}]}